apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urldigest
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/Gkemhcs/genai-url-digest.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
