apiVersion: v1
kind: Namespace
metadata:
   name:  collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: collector-sa 
    namespace: collector 
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
  namespace: collector
  labels:
      app: collector
spec:
  image: otel/opentelemetry-collector-contrib:0.90.0
  serviceAccount: collector-sa
  mode: daemonset
  resources:
    requests:
      cpu: 10m
      memory: 60Mi
    limits:
      memory: 100Mi
  config: |
    receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
  
    exporters:
            googlecloud:

            debug:
              verbosity: detailed

            zipkin:
              endpoint: http://trace.zipkin-svc:9411/api/v2/spans
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug,googlecloud,zipkin]
---
apiVersion: v1
kind: Service 
metadata:
    name: collector-svc 
spec:
    type: ClusterIP
    ports:
    - port: 4318
      targetPort: 4318 
    selector:
        app: collector