apiVersion: v1
kind: Namespace
metadata:
   name: backend
   annotations:
     argocd.argoproj.io/sync-wave: "3"
   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace:  backend
  annotations:
     argocd.argoproj.io/sync-wave: "3"
   
data:
  PGVECTOR_HOST_URL: "pgvector-svc.vectordb"
  PGVECTOR_USER: "gkem"
  PGVECTOR_PASSWORD: "gkem1234"
  PGVECTOR_DATABASE: "urldigest"
  OTLP_ENDPOINT: "otel-deployment-collector.collector"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: backend-sa 
    namespace: backend 
    annotations:
        iam.gke.io/gcp-service-account:  aiplatform-user@genai-url-digest.iam.gserviceaccount.com
        argocd.argoproj.io/sync-wave: "3"
---
apiVersion:  apps/v1
kind: Deployment 
metadata:
   name: backend 
   namespace: backend 
   annotations:
     argocd.argoproj.io/sync-wave: "3"
   
spec:
     replicas: 1
     selector:
       matchLabels:
         
        app: backend
     template:
          metadata:
             labels:
                app: backend 
          spec:
             serviceAccountName: backend-sa
             containers:
             - name: backend-container 
               image: gkem/urldigest-backend:4
               ports:
               - containerPort: 5001
                 name: web-port 
               envFrom:
                - configMapRef:
                    name: backend-config
               startupProbe:
                  httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                  initialDelaySeconds: 60  
                  timeoutSeconds: 5      
                  periodSeconds: 20       
                  successThreshold: 1     
                  failureThreshold: 3 
               readinessProbe:
                 httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                 initialDelaySeconds: 60  
                 timeoutSeconds: 5      
                 periodSeconds: 20       
                 successThreshold: 1     
                 failureThreshold: 3 
               livenessProbe:
                 httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                 initialDelaySeconds: 60  
                 timeoutSeconds: 5      
                 periodSeconds: 20       
                 successThreshold: 1     
                 failureThreshold: 3 
---
apiVersion:  v1
kind: Service 
metadata:
    name: backend-svc 
    namespace: backend
    annotations:
     argocd.argoproj.io/sync-wave: "3"
   
spec:
    type: ClusterIP
    selector:
       app: backend
    ports:
    - targetPort: 5001
      port: 5001
      name: http-port 
    