apiVersion: v1
kind: Namespace
metadata:
   name: backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace:  backend
data:
  PGVECTOR_HOST_URL: "pgvector-svc.vectordb"
  PGVECTOR_USER: "gkem"
  PGVECTOR_PASSWORD: "gkem1234"
  PGVECTOR_DATABASE: "urldigest"
  OTLP_ENDPOINT: "otel-deployment-collector.collector"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: backend-sa 
    namespace: backend 
    annotations:
        iam.gke.io/gcp-service-account:  aiplatform-user@genai-url-digest.iam.gserviceaccount.com
---
apiVersion:  apps/v1
kind: Deployment 
metadata:
   name: backend 
   namespace: backend 
spec:
     replicas: 1
     selector:
       matchLabels:
         
        app: backend
     template:
          metadata:
             labels:
                app: backend 
          spec:
             serviceAccountName: backend-sa
             containers:
             - name: backend-container 
               image: gkem/urldigest-backend:4
               ports:
               - containerPort: 5001
                 name: web-port 
               envFrom:
                - configMapRef:
                    name: backend-config
---
apiVersion:  v1
kind: Service 
metadata:
    name: backend-svc 
    namespace: backend
spec:
    type: ClusterIP
    selector:
       app: backend
    ports:
    - targetPort: 5001
      port: 5001
      name: http-port 
    