apiVersion: v1
kind: Namespace
metadata:
   name: frontend
   annotations:
     argocd.argoproj.io/sync-wave: "4"
   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace:  frontend
  annotations:
     argocd.argoproj.io/sync-wave: "4"
   
data:
  BACKEND_SERVER_URL: "http://backend-svc.backend:5001"
  REDIS_SERVER_URL: "10.127.96.3"
  REDIS_AUTH_STRING: "71ce3ff8-18e7-4226-be10-e3e859b4ad4b"
  OTLP_ENDPOINT: "otel-deployment-collector.collector"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: frontend-sa 
    namespace: frontend 
    annotations:
     argocd.argoproj.io/sync-wave: "4"
   
---
apiVersion:  apps/v1
kind: Deployment 
metadata:
   name: frontend 
   namespace: frontend 
   annotations:
     argocd.argoproj.io/sync-wave: "4"
   
spec:
     replicas: 1
     selector:  
       matchLabels:
         
        app: frontend
     template:
          metadata:
             labels:
                app: frontend 
          spec:
             serviceAccountName: frontend-sa
             containers:
             - name: frontend-container 
               image: gkem/urldigest-frontend:2
               envFrom:
                - configMapRef:
                     name: frontend-config
               ports:
               - containerPort: 5000
                 name: web-port 
               startupProbe:
                  httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                  initialDelaySeconds: 60  
                  timeoutSeconds: 5      
                  periodSeconds: 20       
                  successThreshold: 1     
                  failureThreshold: 3 
               readinessProbe:
                 httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                 initialDelaySeconds: 60  
                 timeoutSeconds: 5      
                 periodSeconds: 20       
                 successThreshold: 1     
                 failureThreshold: 3 
               livenessProbe:
                 httpGet:
                     port: 5000
                     path : /health
                     scheme: HTTP
                 initialDelaySeconds: 60  
                 timeoutSeconds: 5      
                 periodSeconds: 20       
                 successThreshold: 1     
                 failureThreshold: 3 
                  
               
                  
---
apiVersion:  v1
kind: Service 
metadata:
    name: frontend-svc 
    namespace: frontend
    annotations:
     argocd.argoproj.io/sync-wave: "4"
   
spec:
    type: LoadBalancer
    selector:
       app: frontend
    ports:
    - targetPort: 5000 
      port: 80 
      name: http-port 
    