apiVersion: v1
kind: Namespace
metadata:
   name: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace:  frontend
data:
  BACKEND_SERVER_URL: "http://backend-svc.backend:5001"
  REDIS_SERVER_URL: "10.127.96.3"
  REDIS_AUTH_STRING: "71ce3ff8-18e7-4226-be10-e3e859b4ad4b"
  OTLP_ENDPOINT: "otel-deployment-collector.collector"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: frontend-sa 
    namespace: frontend 
---
apiVersion:  apps/v1
kind: Deployment 
metadata:
   name: frontend 
   namespace: frontend 
spec:
     replicas: 1
     selector:  
       matchLabels:
         
        app: frontend
     template:
          metadata:
             labels:
                app: frontend 
          spec:
             serviceAccountName: frontend-sa
             containers:
             - name: frontend-container 
               image: gkem/urldigest-frontend:2
               envFrom:
                - configMapRef:
                     name: frontend-config
               ports:
               - containerPort: 5000
                 name: web-port 
---
apiVersion:  v1
kind: Service 
metadata:
    name: frontend-svc 
    namespace: frontend
spec:
    type: LoadBalancer
    selector:
       app: frontend
    ports:
    - targetPort: 5000 
      port: 80 
      name: http-port 
    