apiVersion: v1
kind: Namespace
metadata:
   name:  collector
---


apiVersion: v1
kind: ServiceAccount
metadata:
    name: collector-sa 
    namespace: collector 
    annotations:
       iam.gke.io/gcp-service-account: trace-appender@genai-url-digest.iam.gserviceaccount.com
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-deployment
  namespace: collector
  labels:
     app: collector-deploy
spec:
  serviceAccount: collector-sa 
  
  image: otel/opentelemetry-collector-contrib:0.90.0
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
      ephemeral-storage: 1Gi
    limits:
      memory: 140Mi
  volumeMounts:
  - mountPath: /var/lib/buffered-telemetry
    name: buffered-telemetry
  volumes:
  - emptyDir: {}
    name: buffered-telemetry
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      k8sattributes:
     
        auth_type: "serviceAccount"
        passthrough: false
       
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
          labels:
            - tag_name: app.label.service
              key: app
              from: pod
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

      attributes:
          actions:
          - key: stage 
            value: development 
            action: insert 
          - key: host.id 
            action: delete
          - key: service.name
            action: upsert 
            value: urldigest 
      resourcedetection:
           detectors : ["env","gcp","system"]
           timeout: 2s
    extensions:
      file_storage:
        directory: /var/lib/buffered-telemetry
        timeout: 10s

    exporters:
      
      googlecloud:

      debug:
        verbosity: detailed

      zipkin:
        endpoint: http://zipkin-svc.trace:9411/api/v2/spans

    service:
     extensions : [file_storage]
     pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection,attributes,k8sattributes]
          exporters: [debug,googlecloud,zipkin]





