apiVersion: v1
kind: Namespace
metadata:
   name:  collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace:  collector
data: 
   config.yaml :  |
           receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
  
           exporters:
            debug:
              verbosity: detailed

            zipkin:
              endpoint: http://trace.zipkin-svc:9411/api/v2/spans
           service:
              pipelines:
                traces:
                  receivers: [otlp]
                  exporters: [debug,zipkin]
    

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: collector-sa 
    namespace: collector 
---
apiVersion:  apps/v1
kind: Deployment 
metadata:
   name: collector 
   namespace: collector 
spec:
     replicas: 1
     selector: 
       matchLabels:
         
        app: collector
     template:
          metadata:
             labels:
                app: collector 
          spec:
             serviceAccountName: collector-sa
             containers:
             - name: collector-container 
               image: otel/opentelemetry-collector:latest
               command: ["--config=/etc/otelcol/config.yaml"]
               ports:
                - containerPort: 4317
                - containerPort: 4318
                - containerPort: 55681
                - containerPort: 55680
               volumeMounts:
                - mountPath: /etc/otelcol
                  name: otelcol-config
             volumes:
              - name: otelcol-config
                configMap:
                  name: otelcol-config
---
apiVersion:  v1
kind: Service 
metadata:
    name: collector-svc 
    namespace: collector
spec:
    type: ClusterIP
    selector:
       app: collector
    ports:
    - targetPort: 4318
      port:  4318
      name: http-port 
    