apiVersion: v1
kind: Namespace
metadata:
   name: vectordb 
   annotations:
     argocd.argoproj.io/sync-wave: "2"
   
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pgvector-sa 
    namespace:  vectordb
    annotations:
     argocd.argoproj.io/sync-wave: "2"
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector-deployment
  namespace: vectordb
  annotations:
     argocd.argoproj.io/sync-wave: "2"
   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - name: pgvector
        image: pgvector/pgvector:pg16
        env:
        - name: POSTGRES_USER
          value: "gkem"
        - name: POSTGRES_PASSWORD
          value: "gkem1234"
        - name: POSTGRES_DB
          value: "urldigest"
        ports:
        - containerPort: 5432
      serviceAccountName: pgvector-sa
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-svc
  namespace: vectordb
  annotations:
     argocd.argoproj.io/sync-wave: "2"
   
spec:
  selector:
    app: pgvector
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
