apiVersion: v1
kind: Namespace
metadata:
   name: trace

   
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: zipkin-sa 
    namespace:  trace
  
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  namespace: trace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        
        ports:
        - containerPort: 9411
      serviceAccountName: zipkin-sa
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  namespace: trace
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - protocol: TCP
    port: 9411
    targetPort: 9411
