pipeline {
    agent {
        docker {
            image 'docker:latest'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' 
        }
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE = 'your-docker-hub-username/backend:latest'
        DOCKER_BUILD_CONTEXT = 'src/backend' // Specify the directory for Docker build context
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                git branch: 'main', url: 'https://github.com/Gkemhcs/genai-url-digest.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the specified directory as build context
                    sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_BUILD_CONTEXT}"
                }
            }
        }
         stage('Push Docker Image') {
            steps {
                script {
                  

                    withDockerRegistry(credentialsId: 'docker-hub-credentials') {
                       
                         sh "docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}"
                    }
                }
            }
        }

        // Add more stages as needed
         stage('Install Trivy') {
            steps {
                script {
                    // Install Trivy
                    sh '''
                    apk update
                    apk add --no-cache wget tar ca-certificates
                    wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz | tar zxvf - -C /usr/local/bin
                    chmod +x /usr/local/bin/trivy
                    '''
                }
            }
        }

        stage('Run Trivy Scan') {
            steps {
                script {
                    // Run Trivy scan and generate HTML report
                    sh 'trivy image --format template --template "@contrib/html.tpl" -o trivy-report.html ${DOCKER_IMAGE}'
                }
            }
        }
       
    }

    post {
        always {
            archiveArtifacts artifacts: 'trivy-report.html', allowEmptyArchive: true
            // Clean up any left over Docker images
            sh 'docker rmi ${DOCKER_IMAGE} || true'
        }
    }
}
