pipeline {
    agent {
        docker {
            image 'docker:latest'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' 
        }
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE = 'gkem/urldigest-frontend:latest'
        DOCKER_BUILD_CONTEXT = 'src/frontend' // Specify the directory for Docker build context
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                git branch: 'main', url: 'https://github.com/Gkemhcs/genai-url-digest.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the specified directory as build context
                    sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_BUILD_CONTEXT}"
                }
            }
        }
         stage('Push Docker Image') {
            steps {
                script {
                  

                    withDockerRegistry(credentialsId: 'docker-hub-credentials') {
                       
                         sh "docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}"
                    }
                }
            }
        }

        
    }

    post {
        always {
           // archiveArtifacts artifacts: 'trivy-report.html', allowEmptyArchive: true
            // Clean up any left over Docker images
            sh 'docker rmi ${DOCKER_IMAGE} || true'
        }
    }
}
