plugin: google.cloud.gcp_compute
zones: # populate inventory with instances in these regions
  - us-central1-a
projects:
  -  PROJECT_ID
filters:
  - status = RUNNING
  - scheduling.automaticRestart = true AND status = RUNNING
  - labels.ansible=master 
keyed_groups:
- prefix: gcp
  key: labels.ansible
auth_kind: application
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'

name_suffix: .example.com
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
